#!/bin/bash

# creation of a flag i
i=1

# Simple for loop from 0 to 1000 by step of 1 for variable volts 
# Note: decimals accepted
for volts in $(seq 0 1 1000)
do 

# to display the value of the variable volts
echo $volts

# to get the data from the scope
get_DSA 1 -o $i

# to wait 1s
sleep 1

# incrementation of the flag i
i=$(($i+1))
# end of for loop
done
